import Header from '@/components/layout/Header';
import { ThemeProvider } from '@/components/layout/ThemeProvider';
import ScrollProgressBar from '@/components/ScrollProgressBar';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});
const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  weight: '45 920',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='kr' suppressHydrationWarning>
      <body
        className={`flex min-h-screen w-full flex-col ${geistSans.variable} ${geistMono.variable} ${pretendard.variable} antialiased`}
      >
        <ThemeProvider>
          <Header />
          <ScrollProgressBar />
          <div className='pl-safe-left pr-safe-right'>
            <div className='max-w-page mx-auto w-full'>{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
